apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: csht2y5kf-go 
  janus-idp.io/tekton: csht2y5kf-go
  backstage.io/kubernetes-id: csht2y5kf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: csht2y5kf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml