apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: csht2y5kf-go-gitops
  description: This is GitOps manifest for csht2y5kf-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=csht2y5kf-go
    backstage.io/kubernetes-id: csht2y5kf-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: csht2y5kf-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:csht2y5kf-go
