apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: csht2y5kf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: csht2y5kf-go 
  name: csht2y5kf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: csht2y5kf-go 
